# vim:ft=kitty

## name: My iTerm2
## author: Copied from the iTerm2 "Default" profile (2026-09-15)
## license: MIT
## blurb: Tango colors as iTerm2 draws them. iTerm2 stores these colors in calibrated RGB, so the values are converted to sRGB.

background #000000
foreground #ffffff
selection_background #c1deff
selection_foreground #000000
url_color #005cbb
cursor #ffffff
cursor_text_color #000000

# normal
color0 #000000
color1 #d81e00
color2 #5ea702
color3 #cfae00
color4 #427ab3
color5 #89658e
color6 #00a7aa
color7 #dbded8

# bright
color8  #686a66
color9  #f54235
color10 #99e343
color11 #fdeb61
color12 #84b0d8
color13 #bc94b7
color14 #37e6e8
color15 #f1f1f0
